title: Applied Linear Algebra
author: Andreas Buttenschoen.
logo: img/nn.png
copyright : "2025"
use_issues_button : true
bibtex_bibfiles:
  - references.bib
sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_togglebutton
  config:
    bibtex_reference_style: author_year
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    myst_enable_extensions:
      - amsmath
      - colon_fence
      - deflist
      - dollarmath
      - html_image
    proof_learning_objectives_template: "proof-learning-objectives"
    proof_titles:
      learning-objectives: "Learning Objectives"
only_build_toc_files: true
execute:
    execute_notebooks: cache
html:
  home_page_in_navbar: true
  use_repository_button: true
  google_analytics_id:
  extra_css:
    - _static/custom.css
launch_buttons:
  colab_url: "https://colab.research.google.com"
repository:
  url: https://github.com/adrs0049/MATH725
